"""Deterministic message composer: compose(category, merchant, trigger, customer?) -> message.

Routing is by trigger.kind. Every handler:
  * anchors on facts that exist in the pushed contexts (never invents numbers, names, prices),
  * states "why now" from the trigger,
  * personalises with the merchant's own numbers/offers/history,
  * ends with a single low-friction CTA.

Triggers generated by the dataset tool carry `{"placeholder": true}` payloads; handlers then fall back
to the merchant's real performance/offer/signal data rather than inventing trigger details.
"""
from __future__ import annotations

import re

from dataclasses import dataclass, field
from typing import Any, Callable, Optional

from .util import (
    CATEGORY_NOUN, CUSTOMER_NOUN, active_offers, catalog_offer, ctr_vs_peer, customer_address,
    customer_prefers_hinglish, customer_regional_greeting, days_between, merchant_regional_greeting, digest_item, expired_offers, first_sentence, fmt_date,
    fmt_day, fmt_time, g, has_signal, humanize, inr, is_placeholder, merchant_name,
    merchant_prefers_hinglish, merchant_salutation, num, offer_matching, pct, pct1, price_in,
    review_theme, seasonal_beat, signal_value, strip_taboos, top_trend,
)


@dataclass
class Ctx:
    category: dict
    merchant: dict
    trigger: dict
    customer: Optional[dict]
    now: Optional[str]
    slug: str = ""
    sal: str = ""
    hi: bool = False
    payload: dict = field(default_factory=dict)

    @property
    def noun(self) -> str:
        return CATEGORY_NOUN.get(self.slug, "business")

    @property
    def people(self) -> str:
        return CUSTOMER_NOUN.get(self.slug, "customers")

    @property
    def locality(self) -> str:
        return str(g(self.merchant, "identity", "locality") or g(self.merchant, "identity", "city") or "")

    def perf(self, key: str) -> Any:
        return g(self.merchant, "performance", key)

    def peer(self, key: str) -> Any:
        return g(self.category, "peer_stats", key)


@dataclass
class Draft:
    body: str
    cta: str  # "binary_yes_no" | "open_ended" | "multi_choice_slot" | "none"
    rationale: str
    template_params: list[str]
    deliverable: str = ""  # what Vera offered to do — reused by the reply engine


def _join(*parts: Optional[str]) -> str:
    return " ".join(p.strip() for p in parts if p and p.strip())


def _yes(ctx: Ctx, en: str, hi: Optional[str] = None) -> str:
    """Single binary CTA, code-mixed when the recipient prefers Hindi."""
    if ctx.hi and hi:
        return f"{hi} Reply YES."
    return f"{en} Reply YES."


def _strip_article(text: str) -> str:
    return re.sub(r"^(a|an|the)\s+", "", text.strip(), flags=re.I)


def _ask(ctx: Ctx, deliverable: str, en: str, hi_verb: str = "draft kar", tail: str = "") -> str:
    """Single binary CTA; natural Hindi-English code-mix when the recipient prefers Hindi."""
    if ctx.hi:
        text = f"Kya main {_strip_article(deliverable)} {hi_verb} doon?"
        if tail:
            text = f"{text} {tail}"
    else:
        text = en
    return f"{text} Reply YES."


def _draft(ctx: Ctx, opener: str, fact: str, cta: str, cta_type: str, rationale: str, deliverable: str) -> Draft:
    body = _join(opener, fact, cta)
    return Draft(body=body, cta=cta_type, rationale=rationale,
                 template_params=[ctx.sal or merchant_name(ctx.merchant), _join(opener, fact), cta],
                 deliverable=deliverable)


# =========================================================================== merchant-facing

def research_digest(ctx: Ctx) -> Draft:
    item = digest_item(ctx.category, ctx.payload.get("top_item_id") or ctx.payload.get("digest_item_id"),
                       kinds=("research", "trend", "tech"))
    if not item:
        return generic(ctx)
    src = item.get("source", "")
    seg = humanize(item.get("patient_segment")) if item.get("patient_segment") else ""
    trial = f"{num(item['trial_n'])}-patient trial: " if item.get("trial_n") else ""
    tie = ""
    hr = g(ctx.merchant, "customer_aggregate", "high_risk_adult_count")
    if seg and "high-risk" in seg and hr:
        tie = f"Directly relevant to the {num(hr)} high-risk adults on your roster."
    elif seg:
        tie = f"Most relevant if you see a lot of {seg}."
    opener = f"{ctx.sal}, new in {src.split(',')[0]} —" if src else f"{ctx.sal}, one research item this week —"
    fact = _join(f"{item.get('title', '')}.", f"{trial}{first_sentence(item.get('summary'))}", tie)
    deliverable = "the 2-min abstract summary + a patient-education WhatsApp you can forward"
    cta = _ask(ctx, deliverable, f"Want me to pull {deliverable}?", "ready kar")
    if src:
        cta = f"{cta} — {src}"
    return _draft(ctx, opener, fact, cta, "binary_yes_no",
                  f"External research digest ({src}) matched to merchant's patient mix; source cited for credibility; reciprocity CTA.",
                  deliverable)


def regulation_change(ctx: Ctx) -> Draft:
    item = digest_item(ctx.category, ctx.payload.get("top_item_id") or ctx.payload.get("digest_item_id"),
                       kinds=("compliance",))
    if not item:
        return generic(ctx)
    deadline = ctx.payload.get("deadline_iso")
    days_left = days_between(ctx.now, deadline) if ctx.now and deadline else None
    when = ""
    if deadline and days_left is not None and days_left >= 0:
        when = f"{days_left} days to the {fmt_date(deadline)} deadline"
    elif deadline:
        when = f"deadline {fmt_date(deadline)}"
    opener = f"{ctx.sal}, compliance heads-up{' (' + when + ')' if when else ''}:"
    fact = _join(f"{item.get('title', '')} ({item.get('source', '')}).", first_sentence(item.get("summary")),
                 f"Action: {item['actionable']}." if item.get("actionable") else "")
    deliverable = f"a 1-page audit checklist for your {ctx.noun} team"
    cta = _ask(ctx, deliverable, f"Want me to draft {deliverable}?", "draft kar")
    return _draft(ctx, opener, fact, cta, "binary_yes_no",
                  "Regulatory change with a hard deadline — loss-aversion framing, cited circular, effort externalised to a checklist.",
                  deliverable)


def cde_opportunity(ctx: Ctx) -> Draft:
    item = digest_item(ctx.category, ctx.payload.get("digest_item_id") or ctx.payload.get("top_item_id"), kinds=("cde",))
    if not item:
        return generic(ctx)
    credits = ctx.payload.get("credits") or item.get("credits")
    fee = ctx.payload.get("fee")
    fee_txt = "free for members" if fee == "free_for_members" else (humanize(fee) if fee else "")
    extra = item.get("actionable", "")
    opener = f"{ctx.sal}, a CDE slot worth blocking:"
    fact = _join(f"{item.get('title', '')} — {fmt_day(item.get('date'))}" + (f", {credits} CDE credits" if credits else "") + ".",
                 str(item.get("summary") or ""),
                 f"({extra})" if extra else (f"({fee_txt})" if fee_txt else ""))
    deliverable = "the registration link + a calendar reminder"
    cta = _ask(ctx, deliverable, f"Want me to send {deliverable}?", "bhej")
    return _draft(ctx, opener, fact, cta, "binary_yes_no",
                  f"CDE event from category digest ({item.get('source', '')}); specific date + credits; one-tap registration offer.",
                  deliverable)


def competitor_opened(ctx: Ctx) -> Draft:
    p = ctx.payload
    own = active_offers(ctx.merchant)
    pos = review_theme(ctx.merchant, "pos")
    strength = ""
    if pos and pos.get("common_quote"):
        strength = f"Your edge is in your reviews: \"{pos['common_quote']}\"."
    elif pos:
        strength = f"Your edge: {pos.get('occurrences_30d')} reviews this month praise {humanize(pos.get('theme'))}."
    if p.get("competitor_name"):
        opener = f"{ctx.sal}, heads-up: {p['competitor_name']} opened {p.get('distance_km', '')} km from you" + \
                 (f" on {fmt_date(p['opened_date'])}" if p.get("opened_date") else "") + "."
        fact = _join(f"They're advertising {p['their_offer']}." if p.get("their_offer") else "",
                     f"Your {own[0]} is live, so skip the price war —" if own else "",
                     (strength[0].lower() + strength[1:]) if (strength and own) else strength)
    else:
        opener = f"{ctx.sal}, a new {ctx.noun} has opened near {ctx.locality} — first weeks are when {ctx.people} compare listings."
        fact = _join(strength or (f"You're at {num(ctx.perf('views'))} views in 30 days." if ctx.perf("views") is not None else ""),
                     f"Your live offer: {own[0]}." if own else f"You have no active offer, so a comparison won't favour you yet.")
    lead = own[0] if own else (catalog_offer(ctx.category) or "your best service")
    deliverable = f"a Google post that leads with your strengths + {lead}"
    cta = _ask(ctx, deliverable, f"Want me to draft {deliverable}?", "draft kar")
    return _draft(ctx, opener, fact, cta, "binary_yes_no",
                  "Competitor trigger framed as loss aversion; differentiates on merchant's own proof (reviews/offer) rather than price.",
                  deliverable)


def _diagnosis(ctx: Ctx) -> list[str]:
    reasons = []
    stale = signal_value(ctx.merchant, "stale_posts")
    if stale is not None:
        reasons.append(f"last Google post was {stale.replace('d', ' days')} ago" if stale else "Google posts are stale")
    if has_signal(ctx.merchant, "no_active_offers") or not active_offers(ctx.merchant):
        reasons.append("no active offer on your listing")
    if has_signal(ctx.merchant, "unverified_gbp") or g(ctx.merchant, "identity", "verified") is False:
        reasons.append("your Google profile is still unverified")
    if has_signal(ctx.merchant, "no_recent_post"):
        reasons.append("no recent Google post")
    return reasons


def perf_dip(ctx: Ctx) -> Draft:
    p = ctx.payload
    metric, delta = p.get("metric"), p.get("delta_pct")
    if is_placeholder(ctx.trigger) or metric is None:
        d7 = g(ctx.merchant, "performance", "delta_7d") or {}
        pairs = [(k.replace("_pct", ""), v) for k, v in d7.items() if isinstance(v, (int, float))]
        pairs.sort(key=lambda kv: kv[1])
        metric, delta = (pairs[0] if pairs else ("views", None))
    base = p.get("vs_baseline")
    cur = ctx.perf(metric)
    if delta is not None and delta < 0:
        opener = f"{ctx.sal}, your {metric} are down {pct(delta)} this week"
    elif delta is not None:
        opener = f"{ctx.sal}, {metric} is your slowest metric this week (only +{pct(delta)})"
    else:
        opener = f"{ctx.sal}, your {metric} have slowed this week"
    opener += f" (baseline ~{base}/week)." if base else (f" — {num(cur)} in the last 30 days." if cur is not None else ".")
    # one driving signal: the single biggest fixable cause (judging guidance: don't stack every fact)
    reasons = _diagnosis(ctx)
    offer = active_offers(ctx.merchant)
    primary = reasons[0] if reasons else ""
    if primary:
        fact = f"The biggest fixable gap I can see: {primary}."
    else:
        peer_ctr = ctr_vs_peer(ctx.merchant, ctx.category)
        fact = (peer_ctr[0].upper() + peer_ctr[1:] + ".") if peer_ctr else ""
    if "offer" in primary or not offer:
        fix, en_verb, hi_verb = (f"an offer like {catalog_offer(ctx.category)} plus a Google post announcing it",
                                 "set up", "aaj hi set up kar")
    elif "unverified" in primary:
        fix, en_verb, hi_verb = "the 5-minute Google verification steps", "walk you through", "aaj hi karwa"
    else:
        fix, en_verb, hi_verb = f"a fresh Google post pushing {offer[0]}", "draft", "aaj hi draft kar"
    deliverable = fix
    cta = _ask(ctx, fix, f"Want me to {en_verb} {fix} today?", hi_verb)
    return _draft(ctx, opener, fact, cta, "binary_yes_no",
                  f"Internal perf dip on {metric}; picks the single biggest fixable cause from merchant signals and one matching fix.",
                  deliverable)


def perf_spike(ctx: Ctx) -> Draft:
    p = ctx.payload
    metric, delta = p.get("metric"), p.get("delta_pct")
    if is_placeholder(ctx.trigger) or metric is None:
        d7 = g(ctx.merchant, "performance", "delta_7d") or {}
        pairs = [(k.replace("_pct", ""), v) for k, v in d7.items() if isinstance(v, (int, float))]
        pairs.sort(key=lambda kv: -kv[1])
        metric, delta = (pairs[0] if pairs else ("views", None))
    driver = humanize(p.get("likely_driver")) if p.get("likely_driver") else ""
    base = p.get("vs_baseline")
    if delta is not None and delta > 0:
        opener = f"{ctx.sal}, nice — {metric} up {pct(delta)} this week"
    else:
        opener = f"{ctx.sal}, your {metric} are holding steady this week"
    opener += (f" vs your ~{base}/week baseline" if base else "") + (f", most likely from your {driver}." if driver else ".")
    cur, peer_key = ctx.perf(metric), f"avg_{metric}_30d"
    peer = ctx.peer(peer_key)
    fact = ""
    if cur is not None and peer:
        if cur >= peer:
            fact = (f"That puts you level with the {num(peer)}-{metric.rstrip('s')} peer average." if cur == peer
                    else f"You're at {num(cur)} {metric} in 30 days — ahead of the {num(peer)} peer average.")
        else:
            fact = f"You're at {num(cur)} {metric} in 30 days; the peer average is {num(peer)} — this spike is how you close the gap."
    fact = _join(fact, "Momentum fades in ~7 days unless you follow up.")
    offer = active_offers(ctx.merchant)
    deliverable = f"a follow-up post" + (f" featuring {offer[0]}" if offer else "") + " while the traffic is warm"
    cta = _ask(ctx, deliverable, f"Want me to draft {deliverable}?", "draft kar")
    return _draft(ctx, opener, fact, cta, "binary_yes_no",
                  "Perf spike — reinforce what worked, quantify vs peers, and convert momentum with one follow-up post.",
                  deliverable)


def seasonal_perf_dip(ctx: Ctx) -> Draft:
    p = ctx.payload
    metric, delta = p.get("metric", "views"), p.get("delta_pct")
    beat = seasonal_beat(ctx.category, keyword="retention") or seasonal_beat(ctx.category, ctx.now)
    members = g(ctx.merchant, "customer_aggregate", "total_active_members")
    when = beat["month_range"] if beat else "this"
    why = str(beat["note"]).split(" — ")[0] if beat else "a seasonal lull"
    opener = (f"{ctx.sal}, your {metric} are down {pct(delta)} this week — expected, not a listing problem: "
              f"{when} is the {why} for {ctx.noun}s.")
    churn = g(ctx.merchant, "customer_aggregate", "monthly_churn_pct")
    peer_churn = ctx.peer("monthly_churn_pct")
    retention = ""
    if churn is not None and members:
        lost = round(members * churn)
        retention = (f"The number that matters now is retention: your monthly churn is {pct(churn)}"
                     + (f" vs {pct(peer_churn)} peer average" if peer_churn is not None else "")
                     + f" — across {num(members)} members that's ~{lost} people a month.")
    elif members:
        retention = f"Best use of this window: keep your {num(members)} active {ctx.people} training; save acquisition spend for the next peak."
    fact = retention or "Best use of this window: retention over acquisition."
    deliverable = "a 4-week attendance challenge message for your current members"
    cta = _ask(ctx, deliverable, f"Want me to draft {deliverable}?", "draft kar")
    return _draft(ctx, opener, fact, cta, "binary_yes_no",
                  "Pre-empts anxiety about an expected seasonal dip; reframes to retention using merchant's member count.",
                  deliverable)


def milestone_reached(ctx: Ctx) -> Draft:
    p = ctx.payload
    if not is_placeholder(ctx.trigger) and p.get("metric"):
        metric = humanize(p["metric"]).replace("count", "").strip() or "review"
        metric = metric if metric.endswith("s") else metric + "s"
        now_v, target = p.get("value_now"), p.get("milestone_value")
        gap = (target - now_v) if isinstance(now_v, int) and isinstance(target, int) else None
        if p.get("is_imminent") and gap and gap > 0:
            opener = f"{ctx.sal}, you're {gap} {metric} away from {num(target)} — currently at {num(now_v)}."
        else:
            opener = f"{ctx.sal}, you just crossed {num(target or now_v)} {metric}."
        peer = ctx.peer("avg_review_count")
        fact = f"Peer avg is {num(peer)}, so you're already ahead — {num(target)} is the number {ctx.people} notice on Google." if peer and now_v and now_v > peer else ""
        deliverable = f"a short review-request WhatsApp for {ctx.people} who visited this week"
    else:
        views, calls = ctx.perf("views"), ctx.perf("calls")
        peer_v = ctx.peer("avg_views_30d")
        opener = f"{ctx.sal}, milestone: {num(views)} Google profile views and {num(calls)} calls in the last 30 days."
        fact = ""
        if views and peer_v:
            ratio = views / peer_v
            fact = f"That's {ratio:.1f}x the {num(peer_v)} peer average." if ratio >= 1 else f"Peer avg is {num(peer_v)} — the next push closes that gap."
        fact = _join(fact, "Good moment to turn visibility into reviews.")
        deliverable = f"a review-request WhatsApp for your recent {ctx.people}"
    cta = _ask(ctx, deliverable, f"Want me to draft {deliverable}?", "draft kar")
    return _draft(ctx, opener, fact, cta, "binary_yes_no",
                  "Milestone framing (goal-gradient effect) with peer comparison; converts to a concrete review-ask.",
                  deliverable)


def dormant_with_vera(ctx: Ctx) -> Draft:
    p = ctx.payload
    days = p.get("days_since_last_merchant_message")
    topic = humanize(p.get("last_topic")) if p.get("last_topic") else ""
    views, calls = ctx.perf("views"), ctx.perf("calls")
    d7 = g(ctx.merchant, "performance", "delta_7d", "views_pct")
    trend = top_trend(ctx.category, specific=True)
    opener = f"{ctx.sal}, it's been {days} days since we last spoke" + (f" (about {topic})" if topic else "") + " — no pitch, one useful number." if days \
        else f"{ctx.sal}, been a while — no pitch, one useful number."
    fact = _join(
        f"{ctx.locality} searches for \"{trend['query']}\" are up {pct(trend['delta_yoy'])} YoY." if trend else "",
        f"Your listing got {num(views)} views and {num(calls)} calls in 30 days" + (f", views {'down' if d7 < 0 else 'up'} {pct(d7)} this week." if isinstance(d7, (int, float)) else ".") if views is not None else "",
    )
    deliverable = "a 2-line breakdown of where those searchers are going instead"
    cta = f"Want {deliverable}? Just reply YES." if not ctx.hi else f"Dekhna chahenge woh searchers kahan ja rahe hain? Reply YES."
    return _draft(ctx, opener, fact, cta, "binary_yes_no",
                  "Dormancy re-engagement via curiosity + a verifiable local trend and own numbers; zero-commitment ask.",
                  deliverable)


def review_theme_emerged(ctx: Ctx) -> Draft:
    p = ctx.payload
    theme = p.get("theme")
    occ, quote, trend = p.get("occurrences_30d"), p.get("common_quote"), p.get("trend")
    if is_placeholder(ctx.trigger) or not theme:
        t = review_theme(ctx.merchant, "neg") or review_theme(ctx.merchant, "pos")
        if t:
            theme, occ, quote = t.get("theme"), t.get("occurrences_30d"), t.get("common_quote")
    if theme:
        opener = f"{ctx.sal}, a review pattern is forming: {occ} reviews in 30 days mention {humanize(theme)}" + (f" ({trend})" if trend else "") + "."
        fact = _join(f"Typical line: \"{quote}\"." if quote else "",
                     "Unanswered, this becomes the first thing new {0} read.".format(ctx.people))
        deliverable = "polite public replies to each + a 1-line fix you can share with staff"
    else:
        opener = f"{ctx.sal}, new reviews are coming in on your {ctx.noun} listing this week."
        fact = f"Peer {ctx.noun}s average {num(ctx.peer('avg_review_count'))} reviews and replying to each lifts trust with new {ctx.people}."
        deliverable = "reply drafts for your latest reviews"
    cta = _ask(ctx, deliverable, f"Want me to draft {deliverable}?", "draft kar")
    return _draft(ctx, opener, fact, cta, "binary_yes_no",
                  "Emerging review theme — quotes the actual review language, loss aversion, effort externalised to reply drafts.",
                  deliverable)


def festival_upcoming(ctx: Ctx) -> Draft:
    p = ctx.payload
    offer = active_offers(ctx.merchant)
    if p.get("festival"):
        days = p.get("days_until")
        opener = f"{ctx.sal}, {p['festival']} is on {fmt_date(p.get('date'))}" + (f" — {days} days out." if days is not None else ".")
        beat = seasonal_beat(ctx.category, keyword="festival") or seasonal_beat(ctx.category, keyword="wedding")
        early = days is not None and days > 45
        fact = _join(f"Category pattern: {beat['month_range']} — {beat['note']}." if beat else "",
                     "Early listings lock in the best slots before the rush." if early else "This is the booking window.")
        pkg = f"a {p['festival']} package built on your {offer[0]}" if offer else f"a {p['festival']} package using {catalog_offer(ctx.category)}"
    else:
        beat = seasonal_beat(ctx.category, keyword="festival") or seasonal_beat(ctx.category, ctx.now)
        opener = f"{ctx.sal}, festival season is coming up for {ctx.noun}s in {ctx.locality}."
        fact = f"Category pattern: {beat['month_range']} — {beat['note']}." if beat else ""
        pkg = f"a festive offer post built on your {offer[0]}" if offer else f"a festive offer post using {catalog_offer(ctx.category)}"
    deliverable = pkg
    cta = _ask(ctx, pkg, f"Want me to draft {pkg}?", "draft kar")
    return _draft(ctx, opener, fact, cta, "binary_yes_no",
                  "Festival trigger with category seasonal data; anchors the package on the merchant's real offer.",
                  deliverable)


def ipl_match_today(ctx: Ctx) -> Draft:
    p = ctx.payload
    when = fmt_time(p.get("match_time_iso"))
    opener = f"{ctx.sal}, {p.get('match', 'IPL match')} at {p.get('venue', ctx.locality)} tonight" + (f", {when}." if when else ".")
    item = digest_item(ctx.category, kinds=("seasonal",))
    offer = active_offers(ctx.merchant)
    if p.get("is_weeknight") is False:
        fact = _join(f"Data point ({item.get('source', '')}): {first_sentence(item.get('summary')) or item['title']}"
                     if item and "ipl" in item.get("id", "").lower() else
                     "Weekend match nights shift orders to home-watch parties.",
                     f"So skip a dine-in promo today and push {offer[0]} as a delivery special instead." if offer
                     else "So lean on delivery tonight rather than a dine-in promo.")
        deliverable = "the delivery banner + an Insta story" + (f" for {offer[0]}" if offer else "")
    else:
        combo = catalog_offer(ctx.category, prefer=("combo", "service_at_price"))
        fact = f"Weeknight matches drive dine-in covers — a match-night combo like {combo} fits." if combo else "Weeknight matches drive dine-in covers."
        deliverable = "a match-night post + table-booking message"
    cta = _ask(ctx, deliverable, f"Want me to make {deliverable}? Live in 10 min.", "bana", tail="10 min mein live.")
    return _draft(ctx, opener, fact, cta, "binary_yes_no",
                  "IPL trigger with category data-informed judgment (weekend vs weeknight); leverages existing offer.",
                  deliverable)


def active_planning_intent(ctx: Ctx) -> Draft:
    p = ctx.payload
    topic = str(p.get("intent_topic") or "")
    last_msg = p.get("merchant_last_message")
    offer = active_offers(ctx.merchant)
    low = topic.lower()
    if "thali" in low or "corporate" in low or "bulk" in low:
        base = price_in(offer[0]) if offer else None
        name = merchant_name(ctx.merchant)
        if base:
            t1, t2, t3 = base - 20, base - 30, base - 40
            draft = (f"{name} Corporate Thali — {ctx.locality} offices:\n"
                     f"• 10+ thalis @ {inr(t1)} each (vs {inr(base)} retail) + free delivery\n"
                     f"• 25+ @ {inr(t2)} each\n"
                     f"• 50+ @ {inr(t3)} each\n"
                     f"• Order on WhatsApp by 5pm the day before; delivered 12:30–1pm")
        else:
            draft = f"{name} Corporate Thali — tiered per-plate price for 10 / 25 / 50+ orders, day-before WhatsApp ordering, fixed lunch delivery slot."
        opener = f"{ctx.sal}, here's a starter version — edit freely:"
        fact = draft
        deliverable = "a 3-line WhatsApp pitch for office admins in your delivery radius"
    elif "kids" in low or "camp" in low or "yoga" in low:
        hist_price = None
        for turn in reversed(ctx.merchant.get("conversation_history") or []):
            hist_price = price_in(str(turn.get("body", "")))
            if hist_price:
                break
        price = inr(hist_price) if hist_price else None
        opener = f"{ctx.sal}, here's the draft {humanize(topic)} — edit freely:"
        fact = ("Kids Yoga Summer Camp (ages 7-12)\n• 4 weeks, 3 classes/week, 45 min each\n"
                + (f"• {price} for the full camp\n" if price else "")
                + "• Small batches, parent WhatsApp update after every week\n"
                + "• Free trial class on Saturday to fill the first batch")
        deliverable = "the GBP post + an Insta carousel for this"
    else:
        opener = f"{ctx.sal}, picking up where you left off" + (f" (\"{last_msg}\")" if last_msg else "") + f" — here's a first cut for {humanize(topic) or 'the plan'}:"
        fact = (f"Built around your live offer {offer[0]}, " if offer else "") + "with a clear price, a start date and one booking channel."
        deliverable = "the full draft"
    cta = _ask(ctx, deliverable, f"Want me to also write {deliverable}?", "bhi likh")
    body = f"{opener}\n\n{fact}\n\n{cta}"
    return Draft(body=body, cta="binary_yes_no",
                 rationale="Merchant already expressed planning intent — skip qualifying and hand over a concrete, priced draft built from their live offer/history.",
                 template_params=[ctx.sal, opener, cta], deliverable=deliverable)


def curious_ask_due(ctx: Ctx) -> Draft:
    trend = top_trend(ctx.category, specific=True)
    thing = "dish" if ctx.slug == "restaurants" else "product" if ctx.slug == "pharmacies" else "service"
    guess = f"Is it {trend['query'].replace(' near me', '').replace(' price', '')}? (searches up {pct(trend['delta_yoy'])} YoY)" if trend else ""
    opener = f"{ctx.sal}, quick one — what's been the most-asked {thing} at {merchant_name(ctx.merchant)} this week?"
    fact = _join(guess, "Tell me and I'll turn it into a Google post + a ready WhatsApp reply for price questions — 5 min of your time." )
    cta = f"Just reply with the {thing} name." if not ctx.hi else f"Bas {thing} ka naam reply kar dijiye."
    return _draft(ctx, opener, fact, cta, "open_ended",
                  "Curious-ask cadence: asking-the-merchant lever + trend-based guess + reciprocity (post + reply drafts).",
                  "a Google post + WhatsApp price reply for that service")


def renewal_due(ctx: Ctx) -> Draft:
    p = ctx.payload
    days = p.get("days_remaining", g(ctx.merchant, "subscription", "days_remaining"))
    plan = p.get("plan", g(ctx.merchant, "subscription", "plan"))
    amount = p.get("renewal_amount")
    views, calls = ctx.perf("views"), ctx.perf("calls")
    opener = f"{ctx.sal}, your {plan} plan renews in {days} days" + (f" ({inr(amount)})." if amount else ".")
    fact = _join(f"In the last 30 days it brought {num(views)} profile views and {num(calls)} calls." if views is not None else "",
                 "If it lapses, profile upkeep and posts pause — that's usually when calls slide.")
    deliverable = "the renewal link"
    cta = _yes(ctx, "Want me to send the renewal link?", "Renewal link bhej doon?")
    return _draft(ctx, opener, fact, cta, "binary_yes_no",
                  "Renewal reminder anchored on value delivered (own numbers) + loss aversion; single binary CTA.",
                  deliverable)


def winback_eligible(ctx: Ctx) -> Draft:
    p = ctx.payload
    days = p.get("days_since_expiry", g(ctx.merchant, "subscription", "days_since_expiry"))
    dip, lapsed = p.get("perf_dip_pct"), p.get("lapsed_customers_added_since_expiry")
    opener = f"{ctx.sal}, it's been {days} days since your plan paused." if days else f"{ctx.sal}, your plan is currently paused."
    fact = _join(f"Since then calls are down {pct(dip)}" + (f" and {lapsed} more {ctx.people} have lapsed." if lapsed else ".") if dip is not None else "",
                 f"Your listing still gets {num(ctx.perf('views'))} views/month — the demand is there.")
    deliverable = "a 1-page plan to win those lapsed customers back"
    cta = _ask(ctx, deliverable, f"Want {deliverable}? No commitment.", "bhej", tail="Koi commitment nahi.")
    return _draft(ctx, opener, fact, cta, "binary_yes_no",
                  "Winback of expired merchant: quantified loss since expiry + no-commitment offer.",
                  deliverable)


def gbp_unverified(ctx: Ctx) -> Draft:
    p = ctx.payload
    uplift = p.get("estimated_uplift_pct")
    path = humanize(p.get("verification_path", "")).replace(" or ", " or a ")
    opener = f"{ctx.sal}, {merchant_name(ctx.merchant)} is still unverified on Google."
    fact = _join(f"Verified listings typically see ~{pct(uplift)} more profile actions." if uplift else "",
                 f"You're getting {num(ctx.perf('views'))} views/month even unverified." if ctx.perf("views") is not None else "",
                 f"Verification is via {path} — about 5 minutes of your time." if path else "")
    deliverable = "the step-by-step verification guide"
    cta = _yes(ctx, f"Want me to walk you through it now?", "Abhi step-by-step karwa doon?")
    return _draft(ctx, opener, fact, cta, "binary_yes_no",
                  "Unverified GBP: quantified uplift + effort cap; single binary CTA.",
                  deliverable)


def supply_alert(ctx: Ctx) -> Draft:
    p = ctx.payload
    item = digest_item(ctx.category, p.get("alert_id"), kinds=("alert",))
    batches = ", ".join(p.get("affected_batches") or [])
    mol = p.get("molecule", "")
    mfr = p.get("manufacturer", "")
    chronic = g(ctx.merchant, "customer_aggregate", "chronic_rx_count")
    opener = f"{ctx.sal}, urgent: voluntary recall on {mol} batches {batches}" + (f" by {mfr}" if mfr else "") + "."
    fact = _join(f"{first_sentence(item.get('summary'))} ({item.get('source', '')})" if item else "",
                 f"You have {num(chronic)} chronic-Rx customers — I can filter who was dispensed these batches." if chronic else "")
    deliverable = "the affected-customer list + a replacement WhatsApp note"
    cta = _ask(ctx, deliverable, f"Want {deliverable}?", "bhej")
    return _draft(ctx, opener, fact, cta, "binary_yes_no",
                  "Urgent supply recall: batch-level specificity, cited alert, derived from merchant's chronic-Rx roster.",
                  deliverable)


def category_seasonal(ctx: Ctx) -> Draft:
    p = ctx.payload
    ups, downs = [], []
    for t in p.get("trends") or []:
        parts = str(t).rsplit("_", 1)
        if len(parts) != 2:
            continue
        name = parts[0].replace("_demand", "").replace("_", " ")
        val = parts[1]
        (ups if val.startswith("+") else downs).append(f"{name} {val}%")
    season = humanize(p.get("season", "this season"))
    opener = f"{ctx.sal}, {season} demand shift is here:"
    fact = _join(f"{', '.join(ups)}" + (f"; {', '.join(downs)}." if downs else "."),
                 "Shelf + counter placement this week decides who captures it.")
    deliverable = "a shelf-reorder checklist + a WhatsApp post for your regulars"
    cta = _ask(ctx, deliverable, f"Want {deliverable}?", "bhej")
    return _draft(ctx, opener, fact, cta, "binary_yes_no",
                  "Category seasonal shift with exact demand deltas; actionable shelf + outreach offer.",
                  deliverable)


_SKIP_KEYS = {"placeholder", "merchant_id", "customer_id", "category", "id", "metric_or_topic"}


def payload_facts(payload: dict, limit: int = 3) -> list[str]:
    """Readable 'why now' facts from an unknown trigger payload: scalar fields only, never invented."""
    out = []
    for k, v in payload.items():
        if k in _SKIP_KEYS or k.endswith("_id") or isinstance(v, (dict, list)) or v in (None, "", True, False):
            continue
        label = humanize(k).replace(" pct", "").replace(" iso", "")
        if isinstance(v, float) and -1 <= v <= 1 and ("pct" in k or "delta" in k):
            val = ("+" if v > 0 else "-") + pct(v)
        elif isinstance(v, str) and re.match(r"^\d{4}-\d{2}-\d{2}", v):
            val = fmt_day(v) if "T" in v else fmt_date(v)
        else:
            val = humanize(v) if isinstance(v, str) and "_" in v else str(v)
        out.append(f"{label}: {val}")
        if len(out) >= limit:
            break
    return out


def weather_heatwave(ctx: Ctx) -> Draft:
    p = ctx.payload
    temp = next((v for k, v in p.items() if "temp" in k and isinstance(v, (int, float))), None)
    city = p.get("city") or g(ctx.merchant, "identity", "city") or ctx.locality
    beat = seasonal_beat(ctx.category, keyword="summer") or seasonal_beat(ctx.category, ctx.now)
    opener = f"{ctx.sal}, heat alert: {city} is at {temp}°C" + (f" ({fmt_date(p['date'])})" if p.get("date") else " today") + "." \
        if temp is not None else f"{ctx.sal}, heatwave alert for {city} today."
    angle = {"restaurants": "footfall drops in peak afternoon heat and delivery picks up",
             "pharmacies": "ORS, electrolytes and sunscreen move fastest",
             "gyms": "members skip afternoon sessions — early-morning and evening slots fill instead",
             "salons": "walk-ins shift to mornings and evenings; cooling treatments sell",
             "dentists": "patients push afternoon appointments — offer morning/evening slots"}.get(ctx.slug, "customer timing shifts on heat days")
    fact = _join(f"On heat days {angle}.", f"Category pattern: {beat['month_range']} — {beat['note']}." if beat else "")
    offer = active_offers(ctx.merchant)
    deliverable = f"a heat-day post" + (f" featuring {offer[0]}" if offer else "") + " for today"
    cta = _ask(ctx, deliverable, f"Want me to put up {deliverable}?", "daal")
    return _draft(ctx, opener, fact, cta, "binary_yes_no",
                  "External heatwave trigger translated into the category-specific demand shift; one same-day action.",
                  deliverable)


def local_news_event(ctx: Ctx) -> Draft:
    p = ctx.payload
    headline = p.get("headline") or p.get("title") or p.get("event") or p.get("summary")
    facts = [f for f in payload_facts(p) if not f.lower().startswith(("headline", "title", "event", "summary"))]
    opener = f"{ctx.sal}, local update near {ctx.locality}: {headline}." if headline else f"{ctx.sal}, a local event near {ctx.locality} today."
    joined = "; ".join(facts)
    fact = _join(joined[:1].upper() + joined[1:] + "." if facts else "",
                 f"It changes who can reach you today — worth telling your {ctx.people} before they decide.")
    deliverable = f"a short WhatsApp + Google post update for your {ctx.people}"
    cta = _ask(ctx, deliverable, f"Want me to draft {deliverable}?", "draft kar")
    return _draft(ctx, opener, fact, cta, "binary_yes_no",
                  "External local-news trigger restated verbatim from the payload (no invented details) + one timely customer update.",
                  deliverable)


def generic(ctx: Ctx) -> Draft:
    kind = humanize(ctx.trigger.get("kind", "update"))
    facts = [] if is_placeholder(ctx.trigger) else payload_facts(ctx.payload)
    views, calls = ctx.perf("views"), ctx.perf("calls")
    opener = f"{ctx.sal}, heads-up on {kind}" + (f" — {'; '.join(facts)}." if facts else f" for {merchant_name(ctx.merchant)}.")
    peer = ctr_vs_peer(ctx.merchant, ctx.category)
    fact = _join(f"Your last 30 days: {num(views)} views, {num(calls)} calls." if views is not None else "",
                 (peer[0].upper() + peer[1:] + ".") if peer else "")
    deliverable = "a one-step action plan for this"
    cta = _ask(ctx, deliverable, f"Want {deliverable}?", "bhej")
    return _draft(ctx, opener, fact, cta, "binary_yes_no",
                  f"Trigger kind '{ctx.trigger.get('kind')}' without a dedicated template — states the trigger's own payload facts, anchored on merchant's numbers.",
                  deliverable)


# =========================================================================== customer-facing

def _cust_open(ctx: Ctx) -> tuple[str, str, str]:
    greet, subject = customer_address(ctx.customer)
    mname = merchant_name(ctx.merchant)
    senior = bool(g(ctx.customer, "identity", "senior_citizen"))
    if senior or (not greet and subject):
        hello = f"Namaste — {mname} here."
    elif greet:
        hello = f"Hi {greet}, {mname} here."
    else:
        hello = f"Hi, {mname} here."
    return hello, greet, subject


def _slots(ctx: Ctx, key: str = "available_slots") -> list[str]:
    return [s.get("label") for s in (ctx.payload.get(key) or []) if isinstance(s, dict) and s.get("label")]


def _pref_slot(ctx: Ctx) -> str:
    pref = g(ctx.customer, "preferences", "preferred_slots")
    return humanize(pref) if pref else ""


def _since_last(ctx: Ctx) -> str:
    last = g(ctx.customer, "relationship", "last_visit")
    d = days_between(last, ctx.now) if ctx.now and last else None
    if d and d > 0:
        return f"{d // 30} months" if d >= 60 else f"{d // 7} weeks" if d >= 14 else f"{d} days"
    return ""


def recall_due(ctx: Ctx) -> Draft:
    p = ctx.payload
    hello, greet, subject = _cust_open(ctx)
    service = humanize(p.get("service_due")) if p.get("service_due") else ""
    last = p.get("last_service_date") or g(ctx.customer, "relationship", "last_visit")
    offer = offer_matching(ctx.merchant, ctx.category, [w for w in service.split() if len(w) > 3]) if service else None
    offer = offer or (active_offers(ctx.merchant)[0] if active_offers(ctx.merchant) else None)
    slots = _slots(ctx)
    who = f"{subject}'s" if subject and subject != greet else "your"
    if service:
        line = f"{who[0].upper() + who[1:]} {service} is due" + (f" — last visit was {fmt_date(last)}." if last else ".")
    else:
        line = f"It's time for {who} next visit" + (f" — last one was {fmt_date(last)}." if last else ".")
    price = f" {offer} applies." if offer else ""
    if slots:
        if customer_prefers_hinglish(ctx.customer):
            cta = f"Aapke liye {len(slots)} slots ready hain: " + " ya ".join(f"{i + 1}) {s}" for i, s in enumerate(slots)) + f". Reply {'/'.join(str(i + 1) for i in range(len(slots)))}, ya apna time bataiye."
        else:
            cta = f"Open slots: " + " or ".join(f"{i + 1}) {s}" for i, s in enumerate(slots)) + f". Reply {'/'.join(str(i + 1) for i in range(len(slots)))}, or tell us a time that works."
        cta_type = "multi_choice_slot"
    else:
        pref = _pref_slot(ctx)
        cta = (f"Reply YES and we'll hold a {pref} slot for you." if pref else "Reply YES and we'll share open slots.")
        if customer_prefers_hinglish(ctx.customer):
            cta = (f"YES reply karein, hum aapke liye {pref} slot hold kar denge." if pref else "YES reply karein, hum slots bhej denge.")
        cta_type = "binary_yes_no"
    body = _join(hello, line + price, cta)
    return Draft(body=body, cta=cta_type,
                 rationale="Customer recall due: real last-visit date, merchant's live offer, real open slots (or stated preference); sent on merchant's behalf.",
                 template_params=[greet or subject or "there", line, cta], deliverable="booking the slot")


def customer_lapsed(ctx: Ctx) -> Draft:
    p = ctx.payload
    hello, greet, subject = _cust_open(ctx)
    days = p.get("days_since_last_visit")
    gap = f"{days // 7} weeks" if days else _since_last(ctx)
    focus = humanize(p.get("previous_focus") or g(ctx.customer, "preferences", "training_focus") or "")
    offer = active_offers(ctx.merchant)
    line = (f"It's been about {gap} since your last visit — happens to everyone, no judgment." if gap
            else "We haven't seen you in a while — happens to everyone, no judgment.")
    if focus:
        line += f" Your {focus} goals are easy to restart."
    extra = f" {offer[0]} is on right now." if offer else ""
    pref = _pref_slot(ctx)
    if customer_prefers_hinglish(ctx.customer):
        cta = f"Ek {pref + ' ' if pref else ''}slot hold kar dein? YES reply karein — koi commitment nahi."
    else:
        cta = f"Want us to hold a {pref + ' ' if pref else ''}slot for you? Reply YES — no commitment."
    body = _join(hello, line + extra, cta)
    return Draft(body=body, cta="binary_yes_no",
                 rationale="Lapsed customer winback: no-shame tone, references their past goal and the merchant's real active offer, zero-commitment CTA.",
                 template_params=[greet or subject or "there", line, cta], deliverable="holding a slot")


def appointment_tomorrow(ctx: Ctx) -> Draft:
    p = ctx.payload
    hello, greet, subject = _cust_open(ctx)
    when = fmt_day(p.get("appointment_iso")) if p.get("appointment_iso") else ""
    service = humanize(p.get("service")) if p.get("service") else ""
    line = "Reminder: your appointment is tomorrow" + (f", {when}" if when else "") + (f" for {service}" if service else "") + "."
    loc = ctx.locality
    if loc:
        line += f" See you at our {loc} {ctx.noun}."
    if customer_prefers_hinglish(ctx.customer):
        cta = "Confirm karne ke liye YES reply karein, ya reschedule ke liye apna time bataiye."
    else:
        cta = "Reply YES to confirm, or tell us a better time to reschedule."
    body = _join(hello, line, cta)
    return Draft(body=body, cta="binary_yes_no",
                 rationale="Appointment reminder for tomorrow — confirm/reschedule in one reply to cut no-shows.",
                 template_params=[greet or subject or "there", line, cta], deliverable="confirming the appointment")


def chronic_refill_due(ctx: Ctx) -> Draft:
    p = ctx.payload
    hello, greet, subject = _cust_open(ctx)
    mols = p.get("molecule_list") or []
    runs_out = p.get("stock_runs_out_iso")
    saved = p.get("delivery_address_saved") or g(ctx.customer, "preferences", "delivery_address") == "saved"
    senior = bool(g(ctx.customer, "identity", "senior_citizen"))
    offers = active_offers(ctx.merchant)
    senior_offer = next((o for o in offers if "senior" in o.lower()), None)
    delivery_offer = next((o for o in offers if "delivery" in o.lower()), None)
    hi = customer_prefers_hinglish(ctx.customer)
    who = subject or ("aapki" if hi else "your")
    if mols:
        if hi:
            line = f"{who} ki {len(mols)} monthly medicines ({', '.join(mols)}) {fmt_date(runs_out)} ko khatam hongi. Same dose, same pack ready hai."
        else:
            line = f"{subject + chr(39) + 's' if subject else 'Your'} {len(mols)} monthly medicines ({', '.join(mols)}) run out on {fmt_date(runs_out)}. Same dose, same pack is ready."
    else:
        line = ("Aapki regular refill ka time aa gaya hai." if hi else "Your regular refill is due.") if ctx.slug == "pharmacies" \
            else ("Aapka routine follow-up due hai." if hi else "Your routine follow-up is due.")
    perks = [o for o in ([senior_offer] if senior and senior_offer else []) + ([delivery_offer] if delivery_offer else []) if o]
    if perks:
        line += (" " + " + ".join(perks) + (" lagu hai." if hi else " applies."))
    if saved:
        line += (" Saved address par home delivery." if hi else " Home delivery to your saved address.")
    if ctx.slug == "pharmacies":
        cta = ("Dispatch ke liye CONFIRM reply karein, ya dosage mein koi badlav ho to bataiye." if hi
               else "Reply CONFIRM to dispatch, or tell us if anything has changed.")
    else:
        pref = _pref_slot(ctx)
        cta = (f"YES reply karein, hum {pref + ' ' if pref else ''}slot book kar denge." if hi
               else f"Reply YES and we'll book a {pref + ' ' if pref else ''}slot for you.")
    body = _join(hello, line, cta)
    return Draft(body=body, cta="binary_yes_no",
                 rationale="Chronic refill due: exact molecules + run-out date, merchant's real senior/delivery offers, one-word confirm.",
                 template_params=[greet or subject or "there", line, cta], deliverable="dispatching the refill")


def trial_followup(ctx: Ctx) -> Draft:
    p = ctx.payload
    hello, greet, subject = _cust_open(ctx)
    trial = p.get("trial_date") or g(ctx.customer, "relationship", "last_visit")
    who = f"{subject}'s" if subject and subject != greet else "your"
    slots = _slots(ctx, "next_session_options")
    line = f"Thanks for {who} trial" + (f" on {fmt_date(trial)}" if trial else "") + "!"
    offer = active_offers(ctx.merchant)
    if offer:
        line += f" To continue, {offer[0]} is available."
    if slots:
        cta = f"Next session: {slots[0]}. Reply YES to book it."
    else:
        pref = _pref_slot(ctx)
        cta = f"Reply YES and we'll book the next {pref + ' ' if pref else ''}session."
    body = _join(hello, line, cta)
    return Draft(body=body, cta="binary_yes_no",
                 rationale="Trial follow-up: references the actual trial date + real next session; single binary CTA.",
                 template_params=[greet or subject or "there", line, cta], deliverable="booking the next session")


def wedding_package_followup(ctx: Ctx) -> Draft:
    p = ctx.payload
    hello, greet, subject = _cust_open(ctx)
    owner = g(ctx.merchant, "identity", "owner_first_name")
    if owner and greet:
        hello = f"Hi {greet}, {owner} from {merchant_name(ctx.merchant)} here."
    days = p.get("days_to_wedding")
    wd = p.get("wedding_date") or g(ctx.customer, "preferences", "wedding_date")
    step = humanize(p.get("next_step_window_open")) if p.get("next_step_window_open") else "pre-bridal prep"
    line = (f"{days} days to your wedding ({fmt_date(wd)})" if days else f"Your wedding on {fmt_date(wd)} is coming up") + \
           f" — this is the right window to start the {step}" + \
           (f", following your bridal trial on {fmt_date(p['trial_completed'])}." if p.get("trial_completed") else ".")
    pref = _pref_slot(ctx) or "Saturday"
    cta = f"Want us to block a {pref} slot for the first session? Reply YES."
    body = _join(hello, line, cta)
    return Draft(body=body, cta="binary_yes_no",
                 rationale="Bridal follow-up: exact days-to-wedding + trial continuity; preferred day honoured; single binary CTA.",
                 template_params=[greet or "there", line, cta], deliverable="blocking the first session")


def unplanned_slot_open(ctx: Ctx) -> Draft:
    hello, greet, subject = _cust_open(ctx)
    slots = _slots(ctx) or _slots(ctx, "slots")
    label = slots[0] if slots else (ctx.payload.get("slot_label") or fmt_day(ctx.payload.get("slot_iso")) if ctx.payload.get("slot_iso") else "")
    offer = active_offers(ctx.merchant)
    line = (f"A slot just opened up: {label}." if label else "A slot just opened up this week.") + (f" {offer[0]} applies." if offer else "")
    cta = ("Aapke liye hold kar dein? YES reply karein." if customer_prefers_hinglish(ctx.customer)
           else "Want it? Reply YES and it's yours.")
    return Draft(body=_join(hello, line, cta), cta="binary_yes_no",
                 rationale="Unplanned slot opened — offered first to this customer with the real slot label and merchant's live offer.",
                 template_params=[greet or subject or "there", line, cta], deliverable="holding the slot")


def customer_generic(ctx: Ctx) -> Draft:
    hello, greet, subject = _cust_open(ctx)
    offer = active_offers(ctx.merchant)
    facts = [] if is_placeholder(ctx.trigger) else payload_facts(ctx.payload, 2)
    line = f"A quick update from us" + (f" ({'; '.join(facts)})" if facts else "") + (f": {offer[0]} is on right now." if offer else ".")
    cta = "Reply YES if you'd like us to book you in."
    return Draft(body=_join(hello, line, cta), cta="binary_yes_no",
                 rationale=f"Customer-scope trigger '{ctx.trigger.get('kind')}' — short, consent-respecting note with merchant's live offer.",
                 template_params=[greet or "there", line, cta], deliverable="booking a visit")


# =========================================================================== routing

MERCHANT_HANDLERS: dict[str, Callable[[Ctx], Draft]] = {
    "research_digest": research_digest,
    "research_digest_release": research_digest,
    "category_research_digest_release": research_digest,
    "weather_heatwave": weather_heatwave,
    "heatwave": weather_heatwave,
    "local_news_event": local_news_event,
    "festival": festival_upcoming,
    "regulation_change": regulation_change,
    "cde_opportunity": cde_opportunity,
    "competitor_opened": competitor_opened,
    "perf_dip": perf_dip,
    "perf_spike": perf_spike,
    "seasonal_perf_dip": seasonal_perf_dip,
    "milestone_reached": milestone_reached,
    "dormant_with_vera": dormant_with_vera,
    "review_theme_emerged": review_theme_emerged,
    "festival_upcoming": festival_upcoming,
    "ipl_match_today": ipl_match_today,
    "active_planning_intent": active_planning_intent,
    "curious_ask_due": curious_ask_due,
    "scheduled_recurring": curious_ask_due,
    "renewal_due": renewal_due,
    "winback_eligible": winback_eligible,
    "gbp_unverified": gbp_unverified,
    "supply_alert": supply_alert,
    "category_seasonal": category_seasonal,
    "category_trend_movement": category_seasonal,
}

CUSTOMER_HANDLERS: dict[str, Callable[[Ctx], Draft]] = {
    "recall_due": recall_due,
    "customer_lapsed_soft": customer_lapsed,
    "customer_lapsed_hard": customer_lapsed,
    "appointment_tomorrow": appointment_tomorrow,
    "chronic_refill_due": chronic_refill_due,
    "trial_followup": trial_followup,
    "wedding_package_followup": wedding_package_followup,
    "bridal_followup": wedding_package_followup,
    "unplanned_slot_open": unplanned_slot_open,
    "customer_lapsed": customer_lapsed,
}

TEMPLATE_NAMES = {k: f"vera_{k}_v1" for k in MERCHANT_HANDLERS}
TEMPLATE_NAMES.update({k: f"merchant_{k}_v1" for k in CUSTOMER_HANDLERS})


def _apply_regional_greeting(draft: Draft, ctx: Ctx, send_as: str) -> None:
    """Tamil / Telugu / Kannada / Marathi-first recipients get a greeting in their language; facts stay in English."""
    if send_as == "merchant_on_behalf":
        word = customer_regional_greeting(ctx.customer)
        if word and not g(ctx.customer, "identity", "senior_citizen"):
            if draft.body.startswith("Hi "):
                draft.body = word + draft.body[2:]
            elif draft.body.startswith("Hi,"):
                draft.body = word + draft.body[2:]
    else:
        word = merchant_regional_greeting(ctx.merchant)
        if word and ctx.sal and draft.body.startswith(ctx.sal):
            draft.body = f"{word} {draft.body}"
            if draft.template_params:
                draft.template_params[0] = f"{word} {draft.template_params[0]}"


def compose_draft(category: dict, merchant: dict, trigger: dict, customer: Optional[dict] = None,
                  now: Optional[str] = None) -> tuple[Draft, str, str]:
    """Returns (draft, send_as, template_name)."""
    category = category or {}
    merchant = merchant or {}
    trigger = trigger or {}
    slug = str(merchant.get("category_slug") or category.get("slug") or "")
    kind = str(trigger.get("kind") or "")
    customer_scope = trigger.get("scope") == "customer" or kind in CUSTOMER_HANDLERS
    ctx = Ctx(category=category, merchant=merchant, trigger=trigger, customer=customer, now=now, slug=slug,
              sal=merchant_salutation(merchant, slug),
              hi=customer_prefers_hinglish(customer) if customer_scope else merchant_prefers_hinglish(merchant),
              payload=trigger.get("payload") if isinstance(trigger.get("payload"), dict) else {})
    if customer_scope and customer:
        handler = CUSTOMER_HANDLERS.get(kind, customer_generic)
        send_as = "merchant_on_behalf"
    else:
        handler = MERCHANT_HANDLERS.get(kind, generic)
        send_as = "vera"
    try:
        draft = handler(ctx)
    except Exception:  # never fail a tick because of one malformed context
        draft = customer_generic(ctx) if send_as == "merchant_on_behalf" else generic(ctx)
    _apply_regional_greeting(draft, ctx, send_as)
    draft.body = strip_taboos(draft.body, category) if "\n" not in draft.body else draft.body
    draft.body = re.sub(r"\s*(https?://\S+|www\.\S+)", "", draft.body)  # URLs are rejected by Meta (-3)
    return draft, send_as, TEMPLATE_NAMES.get(kind, "vera_generic_v1" if send_as == "vera" else "merchant_generic_v1")


def compose(category: dict, merchant: dict, trigger: dict, customer: Optional[dict] = None,
            now: Optional[str] = None) -> dict:
    """Challenge contract (§7.1): returns body, cta, send_as, suppression_key, rationale (+ template info)."""
    draft, send_as, template_name = compose_draft(category, merchant, trigger, customer, now)
    return {
        "body": draft.body,
        "cta": draft.cta,
        "send_as": send_as,
        "suppression_key": str((trigger or {}).get("suppression_key") or f"{(trigger or {}).get('kind')}:{(merchant or {}).get('merchant_id')}"),
        "rationale": draft.rationale,
        "template_name": template_name,
        "template_params": draft.template_params,
        "deliverable": draft.deliverable,
    }
